Table Creation

1) AUTHOR
CREATE TABLE AUTHOR 
(author_ID		VARCHAR(15)		NOT NULL,
book_ID		INTEGER(4)		NOT NULL,
Fname			VARCHAR(15)		NOT NULL,
Lname			VARCHAR(15)		NOT NULL,
PRIMARY KEY(authod_ID),
UNIQUE(authod_ID) );

2)BOOK
CREATE TABLE BOOK
(book_ID		VARCHAR(15)    	        NOT NULL,
 author_ID		VARCHAR(15)    	        NOT NULL,
 publisher_ID		VARCHAR(15)		NOT NULL,
 customer_rating	INT,
 ISBN			VARCHAR(13),
 Price			DECIMAL(3,2)		NOT NULL,
 Condition		VARCHAR(10),
 Title			VARCHAR(50)		NOT NULL,
 Category		VARCHAR(20)		NOT NULL,
 Year			INT			NOT NULL,
 PRIMARY KEY(book_ID),
 FOREIGN KEY(author_ID) REFERENCES AUTHOR(author_ID),
 FOREIGN KEY(publisher_ID) REFERENCES PUBLISHER(publisher_ID) );

3)CUSTOMER
CREATE TABLE CUSTOMER
(customer_ID		VARCHAR(15)		NOT NULL,
 Fname			VARCHAR(15)		NOT NULL,
 Lname			VARCHAR(15)		NOT NULL,
 street1		VARCHAR(30)		NOT NULL,
 street2		VARCHAR(30),
city			VARCHAR(20)		NOT NULL,
country		VARCHAR(15)		NOT NULL,
postal			VARCHAR(10)		NOT NULL,
email			VARCHAR(18),
PRIMARY KEY(customer_ID));

4)EMPLOYEE
CREATE TABLE EMPLOYEE
(employee_ID		VARCHAR(15)		NOT NULL,
 store_ID		VARCHAR(15)		NOT NULL,
 hours_worked	   	   REAL	 		NOT NULL,
 Fname			VARCHAR(15)		NOT NULL,
 Lname			VARCHAR(15)		NOT NULL,
 Email			VARCHAR(30),
 Phone			VARCHAR(15),
 Wage			DECIMAL(2,2)		NOT NULL,
 PRIMARY KEY(employee_ID),
 FOREIGN KEY(store_ID) REFERENCES STORE(store_ID) );

5) ORDER
CREATE TABLE ORDER
(order_ID		VARCHAR(15)		NOT NULL,
customer_ID		VARCHAR(15)		NOT NULL,
date 			DATE			NOT NULL, 
shipping		DECIMAL(3,2)		NOT NULL,
total			DECIMAL(5,2)		NOT NULL,
PRIMARY KEY(order_ID),
FOREIGN KEY(customer_ID) REFERENCES CUSTOMER(customer_ID) );

6) PUBLISHER
CREATE TABLE PUBLISHER
(publisher_ID		VARCHAR(15)		NOT NULL,
 book_ID		VARCHAR(15)		NOT NULL,
 publisher_name	VARCHAR(30)		NOT NULL,
 PRIMARY KEY(publisher_ID) );

7) SHIPPING_ADDRESS
CREATE TABLE SHIPPING_ADDRESS
(username		VARCHAR(20)		NOT NULL,
 Fname			VARCHAR(15)		NOT NULL,
 Lname			VARCHAR(15)		NOT NULL,
 street1		VARCHAR(30)		NOT NULL,
 street2		VARCHAR(30),
 city			VARCHAR(20)		NOT NULL,
 country		VARCHAR(15)		NOT NULL,
 postal		VARCHAR(10)		NOT NULL,
 PRIMARY KEY(username),
 FOREIGN KEY(username) REFERENCES USER(username) );

8) STORE
CREATE TABLE STORE
(store_ID		VARCHAR(15)		NOT NULL,
 street1		VARCHAR(30)		NOT NULL,
 street2		VARCHAR(30),
 city			VARCHAR(20)		NOT NULL,
 country		VARCHAR(15)		NOT NULL,
 postal		VARCHAR(10)		NOT NULL,
 manager_ID		VARCHAR(15)		NOT NULL,
 PRIMARY KEY(store_ID),
 FOREIGN KEY(manager_ID) REFERENCES EMPLOYEE(employee_ID) );

9) STORED_IN
CREATE TABLE STORED_IN
(warehouse_ID		VARCHAR(15)		NOT NULL,
 book_ID		VARCHAR(15)		NOT NULL,
 FOREIGN KEY(warehouse_ID) REFERENCES WAREHOUSE(warehouse_ID),
 FOREIGN KEY(book_ID) REFERENCES BOOK(book_ID) );

10) USER
CREATE TABLE USER
(username		VARCHAR(20)		NOT NULL,
 password		VARCHAR(30)		NOT NULL,
 customer_ID		VARCHAR(15)		NOT NULL,
 PRIMARY KEY(username),
 FOREIGN KEY(customer_ID) REFERENCES CUSTOMER(customer_ID) );

11) WAREHOUSE
CREATE TABLE WAREHOUSE
(warehouse_ID		VARCHAR(15)		NOT NULL,
 book_ID		VARCHAR(15)		NOT NULL,
 street1		VARCHAR(30)		NOT NULL,
 street2		VARCHAR(30),
 city			VARCHAR(20)		NOT NULL,
 country		VARCHAR(15)		NOT NULL,
 postal		VARCHAR(10)		NOT NULL,
 PRIMARY KEY(warehouse_ID),
 FOREIGN KEY(book_ID) REFERENCES BOOK(book_ID) );

12) WRITES
CREATE TABLE WRITES
(publisher_ID		VARCHAR(15)		NOT NULL,
 book_ID		VARCHAR(15)		NOT NULL,
 FOREIGN KEY(publisher_ID) REFERENCES PUBLISHER(publisher_ID),
 FOREIGN KEY(book_ID) REFERENCES BOOK(book_ID) );

13)BUYS
CREATE TABLE BUYS
(customer_ID		INTEGER(4)		NOT NULL,
book_ID		INTEGER(4)		NOT NULL,
order_ID		INTEGER			NOT NULL  DEFAULT 0);

14)HAS
CREATE TABLE HAS
(user_ID		VARCHAR(20)		NOT NULL,
 username		VARCHAR(20)		NOT NULL,
 FOREIGN KEY(user_ID) REFERENCES USER(username),
 FOREIGN KEY(username) REFERENCES SHIPPING_ADDRESS(username) );

15) IN
CREATE TABLE IN
(book_ID		VARCHAR(15)		NOT NULL,
order_ID		VARCHAR(15)		NOT NULL,
FOREIGN KEY(book_ID) REFERENCES BOOK(book_ID) );
